### ISSUE TITLE
Case sensitive parameters

### ISSUE THREAD

**Issue by HAL-NINE-THOUSAND** [MatthiWare/FinancialModelingPrep.NET#16]
Hi Matthi,

Can you confirm this with me? It looks like the period enum isn't working as a parameter

It seems like the parameters are case sensitive:

doesn't work (note capital Q in Quarter)
https://financialmodelingprep.com/api/v3/analyst-estimates/APY.TO?period=Quarter&limit=22&apikey=abc
works:
https://financialmodelingprep.com/api/v3/analyst-estimates/APY.TO?period=quarter&limit=22&apikey=abc 

When it doesn't work it seems to be returning the annual results and the period enum defaults to a capitalised string 

It seems to be on all endpoints (or at least the couple I've tried)

**Comment by Matthiee** [comment]
Hi @HAL-NINE-THOUSAND 

Indeed you are correct. 

Do you want to create a PR for this?

**Comment by Matthiee** [comment]
Hi @HAL-NINE-THOUSAND 

I contacted FMP about this. 
Result is that now both `quarter` and `Quarter` are valid.

**Comment by HAL-NINE-THOUSAND** [comment]
Thanks @Matthiee. This was on my list to do this weekend but great you've got it sorted. 

There's some other changes needed I think (some values can be null, JSON parsing failures etc) but I'll put a PR in for you to review for those when I've got them done.  I didn't with this one as I just wanted to check I wasn't screwing something up on the request ^^

**Comment by Matthiee** [comment]
Hi @HAL-NINE-THOUSAND 

I look forward to the PR.
