### ISSUE TITLE
Add economic indicators

### ISSUE THREAD

**Issue by JZeravik** [MatthiWare/FinancialModelingPrep.NET#69]
Hi, 

would be possible to add economic indicators? 
Gdp, Cpi, Interest rates.. https://site.financialmodelingprep.com/developer/docs/#Economic-Indicator

Thank you

**Comment by Matthiee** [comment]
Hi @JZeravik it should be rather easy to add this. 

Is this something you want to create a PR for?

**Comment by Matthiee** [comment]
Hi @JZeravik 

Version 0.2.0 has been released that includes this feature request. 
https://www.nuget.org/packages/MatthiWare.FinancialModelingPrep/0.2.0

**Comment by JZeravik** [comment]
Hi @Matthiee that's great going to try it. thanks this! .)
