### ISSUE TITLE
Deserialization error when a json property is null

### ISSUE THREAD

**Issue by JZeravik** [MatthiWare/FinancialModelingPrep.NET#82]
These properties can be null:
CompanyProfileResponse.Price
CompanyProfileResponse.Changes
HistoricalPriceItem.UnadjustedVolume

Can you please add these fixes? It seems FmP is using null values more and more?
Thank you

**Comment by Matthiee** [comment]
Part of the problem is FMP doesn't provide the actual typings for the responses. So I have to infer them myself from the responses I get. 

@JZeravik Can you also provide some tickers that cause these properties to be null?

**Comment by JZeravik** [comment]
Hi yes,
BZZUY, SWIR => HistoricalPriceItem.UnadjustedVolume

**Comment by JZeravik** [comment]
FB => CompanyProfileResponse.Price, CompanyProfileResponse.Changes

**Comment by Matthiee** [comment]
Hi @JZeravik I just checked it and FB should now work again, also [v0.2.2](https://www.nuget.org/packages/MatthiWare.FinancialModelingPrep/0.2.2) is available!
